### PR TITLE
[WIP] abstract code a lot more and increase readability aswell as useability.

### PR DESCRIPTION
**Pull request by DevYukine**
Changelog:

- [x] move error handling to ~message event~ has own commandError event now to make code cleaner
- [x] add custom Error Classes
- [x] refactored internal code to pass editable loading message around
- [x] remove a lot of redundant try/catch statements
- [x] changed useless let declarations to const
- [x] improve custom errors
- [x] moving cmdPay logic to message event to reducde redundant code in commands
- [x] update commands because ^
- [x] add new property to Social Class/Constructor (the loading message is now a property)
- [ ] add all loading messages to command constructors [ONGOING]
- [ ] abstract verifyCommand logic so if you miss a mention for example you dont need to pay money for it [ONGOING]
- [ ] add constructor for the default link embed to reduce redundant code (on Command Class)

### CODE REVIEW

**Comment by auguwu** [comment]
fix your engrish kthxbye

**Comment by auguwu** [comment]
rip `base/Social.js`

**Comment by AndrewJWin** [comment]
There are a lot of changes to ``base/Social.js``, so it conflicts with it.

**Comment by DevYukine** [comment]
@AndrewJWin i already fixed them

**Pull request merged**
