### PR TITLE
Possible daily fix

### PR DESCRIPTION
**Pull request by Jackthehaxk21**
*NOT TESTED*
But I see that your getting the score at beginning before changing daily time and money
You then change daily time after it’s set score so effectively not adding points.
This sets time first then points, may fix.

### CODE REVIEW

**Comment by AndrewJWin** [comment]
Please test this before sending a PR, if you require assistance testing, please let one of the staff members or the Contributors know.

**Unless it is an obvious fix, or a minor change to code. All PRs need to be tested prior to being submitted.**

**Comment by Jackthehaxk21** [comment]
@AndrewJWin so sorry i didn't see your comment, ill try to test and if i cant ill get someone to help !

**Comment by Jackthehaxk21** [comment]
@AndrewJWin so sorry i didn't see your comment, ill try to test and if i cant ill get someone to help !

**Comment by Jackthehaxk21** [comment]
@AndrewJWin Sorry unfortunately i cant seem to run it, if you could test it that would be great, or if anyone can. 
and it is kinda a minor change...

**Comment by ghost** [comment]
Any update ?

**Comment by AndrewJWin** [comment]
I'm going to call this PR as dead and request that it be closed.

cc @YorkAARGH

**Comment by JaxkDev** [comment]
Was a small change anyway and I’m pretty sure it was the fix but eh.

**Pull request closed without merging**
