### PR TITLE
New command fortune-cookie

### PR DESCRIPTION
**Pull request by Jackthehaxk21**
Up to you, using the API I mentioned york

### CODE REVIEW

**Comment by AndrewJWin** [comment]
Firstly,
image **MY EYES BURN**.

Secondly, I'd like to see this API in work. With photo proof.

**Comment by auguwu** [comment]
Well, Travis failed. :P probs fix it before make it ;)

**Comment by auguwu** [comment]
and; Does the API even work? Like @AndrewJWin said.

**Comment by Jackthehaxk21** [comment]
Ok to clear up everything I’m giving a public key this key will be valid for 72 hours starting now (9am 15/02/18)
‘M.kytwdhaorb.HHjssjU.jaodjem’
Feel free to test API.

**Comment by Jackthehaxk21** [comment]
https://cdn.discordapp.com/attachments/413604819232620554/413697645140377621/image.png

York you can gain API token from home page
<https://mk-web.glitch.me>

**Comment by YorkAARGH** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
